# Generated by Django 4.0.6 on 2022-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cheonggye_dong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_num',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
